### ISSUE TITLE
使用国服整合版ACT加载cactbot，语言识别为en无法使用

### ISSUE THREAD

**Issue by ghost** [Bluefissure/cactbot_cn#12]
使用了国服整合的ACT，加载cactbot以后，只有部分集合分散点名生效，其余都无效

根据本地化的文档，尝试进行汉化，但发现汉化后条目无效果。
发现在ACT启动时，raidboss的解析language:en。
是因为这个语言解析错误导致无法正常使用吗？
![_{W`$EHPJZ8{)`Z%LKFBSXK](https://user-images.githubusercontent.com/38998206/67182248-49208480-f411-11e9-81d9-a6c572b66e07.png)
![@C@_6%035 _E R3PP{MC0YK](https://user-images.githubusercontent.com/38998206/67182241-44f46700-f411-11e9-9f82-9c474f5d0aeb.png)

ps.另外根据本地化文档，用translate_fight.py只能得出不完整的cn翻译（与此同时其他语言翻译是齐全的）
查看fflogs网站上使用的技能亦无中文技能名翻译，那该如何翻译时间轴？

![image](https://user-images.githubusercontent.com/38998206/67182320-6d7c6100-f411-11e9-80f6-dbd0e97fc20c.png)

**Comment by Bluefissure** [comment]
1. 语言问题，由于解析插件没有`cn`的语言，所以要在`user/raidboss.js`中强行指定语言为`cn`，参考[此处](https://github.com/Bluefissure/cactbot_cn/blob/master/user/raidboss.js#L10) 。
2. 你的replace存在问题，请参考 [本地化教学](https://github.com/Bluefissure/cactbot_cn/blob/master/docs/LocalizeGuide.md) 和 [例子](https://github.com/quisquous/cactbot/blob/master/ui/raidboss/data/05-shb/trial/titania-ex.js#L632 )
3. fflogs不支持的话可以手动导出文件对比查找，或者在[文本检索](https://strings.wakingsands.com)网站检索。（最近总超时，不清楚为什么。）
